plugins { id "com.android.application" }

android {
    namespace "com.cheforder"
    compileSdk 35

    defaultConfig {
        applicationId "com.cheforder"
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName "0.3"
    }

    signingConfigs {
        release {
            storeFile file(System.getenv("CHEFORDER_KEYSTORE_FILE"))
            storePassword System.getenv("KEYSTORE_PASSWORD")
            keyAlias "cheforder"
            keyPassword System.getenv("KEYSTORE_PASSWORD")
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}
